/*
27. Suppose consider we are working on Manufacturing company production house and we have
some machinery in production house can produce some product and we want develop the application
for following purpose 

1. Allocate machinery for production house 
2. Allocate products to machinery 
3. Count the total number of products produced by all machines 
4. Count the all products produced by single specific machine by using its id
5. View all products from production house 
6. View all products produced by particular machine 
For achieve about task we have following class structure 
1. Product class : it is POJO class with field id,name,rate,qty,count 
2. Machinery Class: it is also POJO class which accept Products and return products details it
contain following methods 
//Machinery class contain field id, name, comp, capacity 
//Note: machinery cannot accept product count more than its capacity of products 
//void setProducts(Product p[]): this function can accept number of products for products 
//Product [] getProducts(): this function can return total number product machinery class
//int getTotalProductsCount(): this function can return total products count generated by machines  
//Product getProductById(int id): this function can accept id of product generated by machine
//and return product reference and if product not found return null
//
//. ProductionHouse : this class can accept Machinery and machine class have some details
//Machinery class contain field id, name, comp, capacity 
//Note: machinery cannot accept product count more than its capacity of products 
//ProductionHouse class contain following methods 
//void allocateMachine(Machinery m[]): this method can accept multiple machinery
//Machinery [] getMachinery(): this method can return all machineries with details 
//Product [] getProductsByMachineryId(int id): this function can accept machinery id and return all
//products produced by machine and if id not found return null
//Machinery [] getAllProductionByAllMachine(): this method can return all machinery and its product
//details 
//. ManufacturingHub : this is the main method class and this class contain cases for perform
//above operation
//
//Allocate machinery for production house 
//
//_______________________________________________
//If we want to allocate machinery to production house before machine, we must have production house
//so we required to create class for production house
//If we want to allocate machine to ProductionHouse we required to create classes for machinery 



     //step1 create object (1) of  class production_houseC
	 
	 // step2 create array of machinery and add it into production_house object
	   machinery[] m=new machinery[5];
	   for(int i=0;i<m.length;i++)
	      {
		  m[i]=new machinery();
		    //step3 create array of products and pass to the m[i]
			products []p=new products[5];
			    for(j=0;j<5;j++)
				   {
				     p[i]=new products();
					  p[i].setId(111);
					  p[i].setName("")
				    }
			m[i].setProducts(p);
		  }

*/



import java.util.Scanner;
class Product
{
  private int	id,qty,count;
  private double rate;
  private String name;
  public void setId(int id)
  {
	  this.id=id;
  }
  public void setQty(int qty)
  {
	  this.qty=qty;
  }
  public void setCount(int count)
  {
	  this.count=count;
  }
  public void setRate(double rate)
  {
	  this.rate=rate;
  }
  public void setName(String name)
  {
	  this.name=name;
  }
    //--- all seter and geter
	public int getCount()
	{
		return count;
	}
	public int getId()
	{
		return id;
	}
	
	
}
class Machinery
{
	private int id,capacity;
    private String	name, comp;  
	Product[] p1;//5 products
	public void setId(int id)
  {
	  this.id=id;
  }
  public void setCapacity(int capacity)
  {
	  this.capacity=capacity;
  }
  public void setName(String name)
  {
	  this.name=name;
  }
  public void setComp(String comp)
  {
	  this.comp=comp;
  }
	public int getId()
	{
		return id;
	}
	void setProducts(Product p[])
	{
		p1=p;
	}
	Product [] getProducts()
	{
		return p1;
	}
	int getTotalProductsCount()
	{
	   int count=0;
       for(int i=0;i<p1.length;i++)
	   {
		   count=count+p1[i].getCount();
	   }
		return count;	   
	}
	Product getProductById(int id)
	{
		
		for(int i=0;i<p1.length;i++)
		{
			if(id==p1[i].getId())
			{
				return p1[i];
				
			}
		}
		return null;
		
	}
}
class ProductionHouse
{
	private Machinery[] m;
	
	void allocateMachine(Machinery m[])
	{
		this.m=m;
	}
	Machinery [] getMachinery()
	{
		return m;
	}
	Product [] getProductsByMachineryId(int id)
	{
		Product [] temp=null;
		for(int i=0;i<m.length;i++)
		{
			  if(id==m[i].getId())
			  {
				  temp=m[i].getProducts();
				  break;
			  }
		}
		  return temp;
	}
	Machinery [] getAllProductionByAllMachine()
	{
		return m;
	}
       public Machinery getMachineryById(int id)
	   {
		  Machinery temp=null;
		for(int i=0;i<m.length;i++)
		{
			  if(id==m[i].getId())
			  {
				 temp=m[i];
				 break;
			  }
		}
		  return temp; 
	   }
}







class ManufacturingHub
{
  public static void main(String[]args)
  {
	  Scanner sc=new Scanner(System.in);
	  
	  ProductionHouse ph=new ProductionHouse();
	  
	  Machinery[]m=new Machinery[3];
	   for(int i=0;i<m.length;i++)
	   {
		      m[i]=new Machinery();//1
			   System.out.println("Enter id, name, comp, capacity of Machinery");
				 int id=sc.nextInt();
				 String name=sc.next();
			     String comp=sc.next();
				  int capacity=sc.nextInt();
				   m[i].setId(id);
				   m[i].setName(name);
				   m[i].setComp(comp);
				   m[i].setCapacity(capacity);
				   Product[]p=new Product[capacity];
				   for(int j=0;j<p.length;j++)
				   {
					   p[j]=new Product();
					    System.out.println("Enter id,name,rate,qty,count of Product");
				        int pid=sc.nextInt();
				        String pname=sc.next();
			           double rate=sc.nextDouble();
				       int qty=sc.nextInt();
				       int count=sc.nextInt();
				 
				   p[j].setId(pid);
				   p[j].setName(pname);
				   p[j].setRate(rate);
				   p[j].setQty(qty);
				   p[j].setCount(count);
				   }	   
				   m[i].setProducts(p);
	   }
	   
		ph.allocateMachine(m);
		m=new Machinery[10];
		//3. Count the total number of products produced by all machines 
	    int pcount=0;
		Machinery []tempM=ph.getMachinery();
		  for(int i=0;i<tempM.length;i++)
		  {
			  pcount=pcount+tempM[i].getTotalProductsCount();
		  }
		  System.out.println("total number of products produced by all machines="+pcount);
		  
		  //4. Count the all products produced by single specific machine by using its id
		  System.out.println("Enter Machinery ID");
		  int mid=sc.nextInt();
		  
		  Machinery m3 =ph.getMachineryById(mid);
		    if(m3==null)
			{
				System.out.println("Machinery not found");
			}
			else
			{
				pcount=m3.getTotalProductsCount();
				System.out.println("all products produced="+pcount);
			}
		  
  }  
}
